services:
  db:
    image: mysql:latest
    container_name: cool_container
    restart: unless-stopped
    environment:
      MYSQL_DATABASE: cool_db
      MYSQL_USER: pablo
      MYSQL_PASSWORD: pablo123
      MYSQL_ROOT_PASSWORD: root123
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql
volumes:
  db_data: